# Generated by Django 6.0.3 on 2026-03-10 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, message='Имя должно быть не короче 2 символов')], verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(16, message='Возраст должен быть от 16 до 60'), django.core.validators.MaxValueValidator(60, message='Возраст должен быть от 16 до 60')], verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email')], verbose_name='Email')),
                ('course', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Курс должен быть от 1 до 6'), django.core.validators.MaxValueValidator(6, message='Курс должен быть от 1 до 6')], verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['id'],
            },
        ),
    ]
